### ISSUE TITLE
Class Voucherify\VoucherifyClient does not exist

### ISSUE THREAD

**Issue by chris-huffman** [voucherifyio/magento-extension#7]
When trying to load the Payment Method step of the checkout, I get an error that the class Voucherify\\VoucherifyClient does not exist. This is during the set-payment-information ajax call.

Upon further inspection, this class is referenced in a few places throughout the module. Does this reference need to be updated? Or this class included?

**Comment by mandraszyk** [comment]
Hello, Thank you for reporting this issue!
The readme page will be updated shortly with the missing step.
Voucheirfy PHP SDK module is required and can be installed by executing `composer require rspective/voucherify` on the Magento server.

**Comment by chris-huffman** [comment]
@mandraszyk  Thanks! That solved my problem.
