### ISSUE TITLE
Wrong API Url

### ISSUE THREAD

**Issue by chris-huffman** [voucherifyio/magento-extension#8]
When I input a Voucherify discount code in checkout, I get an error message asking me to change the API URL I'm using. However, I don't see any configuration or method of changing this URL.

{"code":403,"message":"Wrong API endpoint","details":"Given project is bound to different API endpoint, you should use: https://us1.api.voucherify.io","key":"wrong_api_endpoint"}

**Comment by mandraszyk** [comment]
Hello, Thank you for reporting this issue!
The settings page will be updated shortly with the API URL form field.

**Comment by chris-huffman** [comment]
@mandraszyk  Thanks! That resolved my issue.
